services:
  postgres:
    image: postgres:15
    container_name: desafiofinal_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: desafiofinaldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  desafiofinal.api:
    image: desafiofinalapi
    build:
      context: .
      dockerfile: DesafioFinal.Api/Dockerfile
    container_name: desafiofinal_api
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=desafiofinaldb;Username=admin;Password=admin123
    ports:
      - "8080:8080"
      - "8081:8081"

volumes:
  pgdata:
